<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TTF-BLR-SANTOSHKOUJALAGI" name="com.tetherfi.test.reports.OCMChatbotInteractionreportTest" tests="51" failures="5" timestamp="2021-11-16T00:41:02 IST" time="1615.474" errors="3">
  <testcase name="ShowReport" time="23.163" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ShowChatbotInteractionReportInNewTab" time="19.258" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="database" time="62.088" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest">
    <failure type="java.lang.AssertionError" message="UI and Database data mismatch did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: UI and Database data mismatch did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.tetherfi.test.reports.OCMChatbotInteractionreportTest.database(OCMChatbotInteractionreportTest.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- database -->
  <testcase name="VerifySearchByFeature" time="107.603" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.tetherfi.test.reports.OCMChatbotInteractionreportTest.VerifySearchByFeature(OCMChatbotInteractionreportTest.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifySearchByFeature -->
  <testcase name="VerifySearchIsEqualTo" time="28.039" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="searchwithoutSearchTextbox" time="21.705" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifySearchIsNotEqualTo" time="47.676" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifySearchContains" time="45.981" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifySearchDoesNotContains" time="27.397" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifySearchStartsWith" time="27.527" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifySearchEndsWith" time="45.537" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="SearchClearSearch" time="21.131" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="verifyAdvancedSearch" time="50.060" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ClearfiltersAdvSrch" time="22.515" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="GroupBy" time="22.498" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="verifyAdvancedSearchAndCriteria" time="63.455" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="verifyAdvancedSearchORCriteria" time="66.774" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="verifyAdvancedSearchIsNotEqualTo" time="48.748" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="verifyAdvancedSearchcontains" time="50.728" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="verifyAdvancedSearchDoesnotcontains" time="30.682" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="verifyAdvancedSearchStartswith" time="31.106" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="verifyAdvancedSearchEndswith" time="30.362" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifySorting" time="22.518" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest">
    <failure type="java.lang.AssertionError" message="item per page assertion failed did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: item per page assertion failed did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.tetherfi.test.reports.OCMChatbotInteractionreportTest.VerifySorting(OCMChatbotInteractionreportTest.java:286)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifySorting -->
  <testcase name="ScheduleOCMChatbotInteractionReport" time="16.601" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ExportReport" time="14.974" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ViewDownloadedReportInReportsDownloadPage" time="11.036" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifyViewDownloadedOcmChatbotInteractionReportInReportsDownloadPage" time="32.214" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.tetherfi.utility.ExcelReader.getExcelData(ExcelReader.java:126)
at com.tetherfi.pages.OCMReportsPage.verifyExportedSheet(OCMReportsPage.java:6658)
at com.tetherfi.test.reports.OCMChatbotInteractionreportTest.VerifyViewDownloadedOcmChatbotInteractionReportInReportsDownloadPage(OCMChatbotInteractionreportTest.java:326)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyViewDownloadedOcmChatbotInteractionReportInReportsDownloadPage -->
  <testcase name="ShowReportForDateRange" time="16.660" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ShowReportInNewPageForDateRange" time="17.602" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ExportReportForDateRange" time="16.711" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ScheduleReportforDateRange" time="15.844" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ViewDownloadedReportInReportsDownloadPageForDateRange" time="8.564" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifyDownloadedReportDataForDateRange" time="31.525" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.tetherfi.utility.ExcelReader.getExcelData(ExcelReader.java:126)
at com.tetherfi.pages.OCMReportsPage.verifyExportedSheet(OCMReportsPage.java:6658)
at com.tetherfi.test.reports.OCMChatbotInteractionreportTest.VerifyDownloadedReportDataForDateRange(OCMChatbotInteractionreportTest.java:388)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyDownloadedReportDataForDateRange -->
  <testcase name="DeleteRecordWithoutDeleteReasonInReportsDownload" time="10.807" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifyCancelBtnAtReportsDownload" time="32.605" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="DeleteRecord" time="10.943" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ClearAll" time="14.227" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="OCMWindow" time="19.287" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifyDropdownForAllTheColumns" time="46.548" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifyColumnsHeaderEnable" time="53.392" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifyColumnsHeaderDisable" time="66.872" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifyArrowMoveForPreviousAndNextPage" time="20.730" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifyArrowMoveForFirstAndLastPage" time="22.867" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest">
    <failure type="java.lang.AssertionError" message="arrow move for first and last page assertion failed did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: arrow move for first and last page assertion failed did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.tetherfi.test.reports.OCMChatbotInteractionreportTest.VerifyArrowMoveForFirstAndLastPage(OCMChatbotInteractionreportTest.java:499)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyArrowMoveForFirstAndLastPage -->
  <testcase name="VerifyTotalNumberOfItemsPerPageDetails" time="18.487" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifyNumberOfItemsPerPageSelection" time="53.437" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ExportPage" time="22.597" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifyExportedData" time="32.003" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.tetherfi.test.reports.OCMChatbotInteractionreportTest.VerifyExportedData(OCMChatbotInteractionreportTest.java:546)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyExportedData -->
  <testcase name="SchedulereportinChatbotInteractionPage" time="19.014" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ExportToExcel" time="17.495" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="ViewDownloadedReportInReportDownloadsPage" time="22.049" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest"/>
  <testcase name="VerifyDownloadedOcmChatbotInteractionReport" time="33.832" classname="com.tetherfi.test.reports.OCMChatbotInteractionreportTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.tetherfi.utility.ExcelReader.getExcelData(ExcelReader.java:126)
at com.tetherfi.pages.OCMReportsPage.verifyExportedSheet(OCMReportsPage.java:6658)
at com.tetherfi.test.reports.OCMChatbotInteractionreportTest.VerifyDownloadedOcmChatbotInteractionReport(OCMChatbotInteractionreportTest.java:595)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyDownloadedOcmChatbotInteractionReport -->
</testsuite> <!-- com.tetherfi.test.reports.OCMChatbotInteractionreportTest -->
